spring:
  datasource:
    url: jdbc:h2:mem:parver;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
      path: /h2-console

parver:
  security:
    jwt:
      secret: dev-secret-key-that-is-at-least-32-bytes-long-for-hmac-sha256
  push:
    vapid:
      public-key: BBzXPhLlPyQtt9wZRAy_DvbDl4blAckOCMjDEfrurK_oH39xqTn31onFaan9GxWWjrgw4ULgcN6NiIu-Uxx6eRc
      private-key: jF8zZD9gF7wD5eElW-74HUGw-3AKLeMYHKv1wcBaE0Q
      subject: mailto:dev@parver.local
